services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: flowers_sql

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Shereen@123"

    ports:
      - "1433:1433"

    volumes:
      - sql_data:/var/opt/mssql

  flowersapi:
    build:
      context: .
      dockerfile: FlowersApp/Dockerfile

    container_name: flowers_api
    depends_on:
      - sqlserver

    ports:
      - "8080:80"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__cs: "Server=sqlserver;Database=Planty;User Id=sa;Password=Shereen@123;TrustServerCertificate=True;"

volumes:
  sql_data: