
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server

    container_name: flowers_sql

    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Shereen@123"

    ports:
      - "5000:1433"

    volumes:
      - sql_data:/var/opt/mssql


  flowersapi:
    build:
      context: .
      dockerfile: FlowersApp/Dockerfile

    container_name: flowers_api

    depends_on:
      - sqlserver

    ports:
      - "8080:80"

    environment:
      ASPNETCORE_ENVIRONMENT: Development

      # connection string inside container
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=Planty;User Id=sa;Password=shereen@123;TrustServerCertificate=True;"